services:
  postgres:
    image: postgres:16
    container_name: tasktracker-postgres
    env_file: ../.env
    environment:
      SPRING_DATASOURCE_URL: ${DB_URL}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U taskuser -d tasktracker"]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  pgdata: